### ISSUE TITLE
Common Lisp implementation

### ISSUE THREAD

**Issue by mtstickney** [pvginkel/ProgressEncode#1]
First off, thanks for doing this project: it has saved my bacon in a pretty significant way (we have a web application with existing users whose passwords are hashed with, you guessed it, `ENCODE()`).

I've ported your code to Common Lisp ([here](https://github.com/mtstickney/oe-encode), licensed CC0), which you're welcome to include here if you like. I'm not sure how you'd want to do that: I kind of need it in my own repository for distribution purposes. Perhaps a git subtree? Plain old file copy? In any case, don't feel obligated; it just seemed like a good idea to make it available here as well.

**Comment by pvginkel** [comment]
Teriffic, thanks. I've added your project as a sub module.
